services:
  hdhomerun-epg:
    build: .
    container_name: hdhomerun-epg
    ports:
      - "8000:8000"
    environment:
      - HDHOMERUN_HOST=10.1.1.43
      - HDHOMERUN_EPG_DAYS=7
      - HDHOMERUN_EPG_HOURS=3
      - HDHOMERUN_DEBUG_MODE=on
    restart: unless-stopped
